service: connector-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  # environment variables removed - AWS provides these automatically
  timeout: 29

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

plugins:
  - serverless-offline